"""Re-initialization

Revision ID: cc61ffaf8de8
Revises: 
Create Date: 2025-12-28 13:46:58.575828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc61ffaf8de8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dorm_building',
    sa.Column('building_id', sa.Integer(), nullable=False, comment='楼宇ID'),
    sa.Column('building_name', sa.String(length=50), nullable=False, comment='楼名'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='地理位置'),
    sa.Column('admin_contact', sa.String(length=20), nullable=True, comment='宿管办公室电话'),
    sa.PrimaryKeyConstraint('building_id')
    )
    with op.batch_alter_table('dorm_building', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dorm_building_building_name'), ['building_name'], unique=True)

    op.create_table('spare_part',
    sa.Column('part_id', sa.Integer(), nullable=False, comment='配件ID'),
    sa.Column('part_name', sa.String(length=100), nullable=False, comment='配件名称'),
    sa.Column('spec', sa.String(length=50), nullable=True, comment='规格型号'),
    sa.Column('current_stock', sa.Integer(), nullable=False, comment='当前库存量'),
    sa.Column('unit', sa.String(length=10), nullable=True, comment='单位'),
    sa.Column('warning_line', sa.Integer(), nullable=False, comment='预警阈值'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='实时价格'),
    sa.CheckConstraint('current_stock >= 0', name='ck_stock_non_negative'),
    sa.PrimaryKeyConstraint('part_id'),
    sa.UniqueConstraint('part_name', 'spec', name='uq_part_name_spec')
    )
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_part_part_name'), ['part_name'], unique=False)

    op.create_table('sys_user',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('account', sa.String(length=50), nullable=False, comment='登录账号'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('password', sa.String(length=256), nullable=False, comment='登录密码'),
    sa.Column('role', sa.Enum('STUDENT', 'WORKER', 'ADMIN', name='userrole'), nullable=False, comment='角色'),
    sa.Column('email', sa.String(length=120), nullable=False, comment='邮箱'),
    sa.Column('building_id', sa.Integer(), nullable=True, comment='所属宿舍楼ID'),
    sa.Column('room_no', sa.String(length=10), nullable=True, comment='房间号'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态: 1-在校/在职, 0-离校/离职'),
    sa.ForeignKeyConstraint(['building_id'], ['dorm_building.building_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_user_account'), ['account'], unique=True)
        batch_op.create_index(batch_op.f('ix_sys_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_sys_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_user_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_user_username'), ['username'], unique=False)

    op.create_table('repair_order',
    sa.Column('order_id', sa.Integer(), nullable=False, comment='报修单ID'),
    sa.Column('submitter_id', sa.Integer(), nullable=False, comment='报修人ID'),
    sa.Column('repair_building_id', sa.Integer(), nullable=False, comment='故障所在楼ID'),
    sa.Column('repair_location', sa.String(length=10), nullable=False, comment='故障位置'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='报修主题'),
    sa.Column('description', sa.Text(), nullable=True, comment='详细描述'),
    sa.Column('image_urls', sa.Text(), nullable=True, comment='故障图片url'),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False, comment='状态'),
    sa.Column('submit_time', sa.DateTime(), nullable=False, comment='提交时间'),
    sa.Column('finish_time', sa.DateTime(), nullable=True, comment='实际完成时间'),
    sa.Column('rating', sa.SmallInteger(), nullable=True, comment='学生评分'),
    sa.Column('feedback', sa.String(length=255), nullable=True, comment='学生反馈'),
    sa.ForeignKeyConstraint(['repair_building_id'], ['dorm_building.building_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitter_id'], ['sys_user.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('maintenance_record',
    sa.Column('record_id', sa.Integer(), nullable=False, comment='记录ID'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='关联报修单ID'),
    sa.Column('worker_id', sa.Integer(), nullable=False, comment='实际维修人ID'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始维修时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束维修时间'),
    sa.Column('result_desc', sa.Text(), nullable=True, comment='维修结果/故障原因分析'),
    sa.Column('labor_cost', sa.Numeric(precision=10, scale=2), nullable=True, comment='人工/时间成本估算'),
    sa.ForeignKeyConstraint(['order_id'], ['repair_order.order_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['sys_user.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('order_assign',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['repair_order.order_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'order_id')
    )
    op.create_table('part_usage_detail',
    sa.Column('usage_id', sa.Integer(), nullable=False, comment='流水号'),
    sa.Column('record_id', sa.Integer(), nullable=False, comment='关联维修记录ID'),
    sa.Column('part_id', sa.Integer(), nullable=False, comment='关联配件ID'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='消耗数量'),
    sa.ForeignKeyConstraint(['part_id'], ['spare_part.part_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['maintenance_record.record_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('usage_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part_usage_detail')
    op.drop_table('order_assign')
    op.drop_table('maintenance_record')
    op.drop_table('repair_order')
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_user_username'))
        batch_op.drop_index(batch_op.f('ix_sys_user_status'))
        batch_op.drop_index(batch_op.f('ix_sys_user_role'))
        batch_op.drop_index(batch_op.f('ix_sys_user_email'))
        batch_op.drop_index(batch_op.f('ix_sys_user_account'))

    op.drop_table('sys_user')
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_part_part_name'))

    op.drop_table('spare_part')
    with op.batch_alter_table('dorm_building', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dorm_building_building_name'))

    op.drop_table('dorm_building')
    # ### end Alembic commands ###
